name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README with GitHub Stats
        run: |
          cat <<EOF > README.md
# 👋 Hello, I'm Sam (Saidahmad)

![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&size=35&pause=1000&color=38C2FF&vCenter=true&width=435&lines=Software+Engineer;Passionate+about+AI;Lifelong+Learner)

---

## 🚀 About Me

- 🌍 Based in **Seoul, South Korea**
- 🕒 **Time Zone**: UTC+09:00
- 🎓 **Studied at Gachon University**
- ✉️ Contact me at: [lionuz669@gmail.com](mailto:lionuz669@gmail.com)

---

![Contributions in the last year](https://github-readme-activity-graph.vercel.app/graph?username=Saidakhmad77&theme=react-dark&hide_border=true)

---

## 💼 Skills & Tools

![Python](https://img.shields.io/badge/-Python-05122A?style=flat&logo=python)&nbsp;
![JavaScript](https://img.shields.io/badge/-JavaScript-05122A?style=flat&logo=javascript)&nbsp;
![HTML](https://img.shields.io/badge/-HTML-05122A?style=flat&logo=HTML5)&nbsp;
![CSS](https://img.shields.io/badge/-CSS-05122A?style=flat&logo=CSS3&logoColor=1572B6)&nbsp;
![Git](https://img.shields.io/badge/-Git-05122A?style=flat&logo=git)&nbsp;
![GitHub](https://img.shields.io/badge/-GitHub-05122A?style=flat&logo=github)&nbsp;
![VS Code](https://img.shields.io/badge/-VS%20Code-05122A?style=flat&logo=visual-studio-code&logoColor=007ACC)&nbsp;

---

## 🔍 Pinned Repositories

<div align="center">
  <a href="https://github.com/Saidakhmad77/Blackjack_python">
    <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=Saidakhmad77&repo=Blackjack_python&theme=radical&hide_border=true&bg_color=0D1117&title_color=38C2FF&icon_color=38C2FF" />
  </a>
  <a href="https://github.com/Saidakhmad77/Number_Guessing_game_python">
    <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=Saidakhmad77&repo=Number_Guessing_game_python&theme=radical&hide_border=true&bg_color=0D1117&title_color=38C2FF&icon_color=38C2FF" />
  </a>
  <a href="https://github.com/Saidakhmad77/Weather_Forecast_Python">
    <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=Saidakhmad77&repo=Weather_Forecast_Python&theme=radical&hide_border=true&bg_color=0D1117&title_color=38C2FF&icon_color=38C2FF" />
  </a>
  <a href="https://github.com/Saidakhmad77/Currency_change_converter">
    <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=Saidakhmad77&repo=Currency_change_converter&theme=radical&hide_border=true&bg_color=0D1117&title_color=38C2FF&icon_color=38C2FF" />
  </a>
</div>

---

## 📊 GitHub Stats

![GitHub Stats](https://github-readme-stats.vercel.app/api?username=Saidakhmad77&show_icons=true&theme=radical&hide_border=true&bg_color=0D1117&title_color=38C2FF&icon_color=38C2FF)

![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=Saidakhmad77&layout=compact&theme=radical&hide_border=true&bg_color=0D1117&title_color=38C2FF&icon_color=38C2FF)
EOF

      - name: Commit changes
        run: |
          git config --local user.email "lionuz669@gmail.com"
          git config --local user.name "Sam (Saidahmad)"
          git add README.md
          git commit -m "Automated update of README"
          git push
